# Generated by Django 4.2.1 on 2023-05-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_catagoery',
            name='catagoery',
        ),
        migrations.DeleteModel(
            name='catagoery',
        ),
        migrations.DeleteModel(
            name='sub_catagoery',
        ),
    ]
